export const ventasHistorialMonedaDetalle = `
SELECT 
    MONEDA_HISTORIAL.MONEDA_CODIGO,
    MONEDA_HISTORIAL.FACTOR_CAMBIO, 
    MONEDA.NOMBRE, 
    extract (year from FECHA_HORA) AS ANO, 
    extract (month from FECHA_HORA) AS MES, 
    extract (day from FECHA_HORA) AS DIA
FROM MONEDA INNER JOIN MONEDA_HISTORIAL ON MONEDA.CODIGO = MONEDA_HISTORIAL.MONEDA_CODIGO
WHERE (MONEDA_HISTORIAL.MONEDA_CODIGO='02')
ORDER BY extract (year from FECHA_HORA) DESC , extract (month from FECHA_HORA) DESC , extract (day from FECHA_HORA) DESC
`

export const ventasRangoTiempoDia = (lastDate,) =>{
    return  `
        SELECT 
            extract (year from ventas.FECHA_Y_HORA) AS ANO, 
            extract (month from ventas.FECHA_Y_HORA) AS MES, 
            extract ( day from ventas.FECHA_Y_HORA) AS DIA
        FROM VENTAS
        ${ lastDate ? `WHERE ventas.FECHA_Y_HORA >='${lastDate}'`:""}
        GROUP BY extract (year from ventas.FECHA_Y_HORA), extract (month from ventas.FECHA_Y_HORA), extract ( day from ventas.FECHA_Y_HORA)
        ORDER BY extract (year from ventas.FECHA_Y_HORA) DESC , extract (month from ventas.FECHA_Y_HORA) DESC , extract ( day from ventas.FECHA_Y_HORA) DESC

        
    `
}

export const historialTasaBCVSQL = (lastDate)=>{
    return `
    SELECT 
        ( Cst_VENTAS_RANGO_TIEMPO_DIA.ANO || '-' || Cst_VENTAS_RANGO_TIEMPO_DIA.MES || '-' ||  Cst_VENTAS_RANGO_TIEMPO_DIA.DIA  ) as ID,
        Cst_VENTAS_RANGO_TIEMPO_DIA.ANO,
        Cst_VENTAS_RANGO_TIEMPO_DIA.MES,
        Cst_VENTAS_RANGO_TIEMPO_DIA.DIA,
        Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.MONEDA_CODIGO, 
        Avg(Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.FACTOR_CAMBIO) AS PromedioDeFACTOR_CAMBIO,
        Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.NOMBRE
    FROM 
        (${ventasRangoTiempoDia(lastDate)}) as Cst_VENTAS_RANGO_TIEMPO_DIA 
        LEFT JOIN (${ventasHistorialMonedaDetalle}) as Cst_VENTAS_HISTORIAL_MONEDA_DETALLE
        ON
            (Cst_VENTAS_RANGO_TIEMPO_DIA.ANO = Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.ANO) 
            AND (Cst_VENTAS_RANGO_TIEMPO_DIA.MES = Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.MES) 
            AND (Cst_VENTAS_RANGO_TIEMPO_DIA.DIA = Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.DIA)
    GROUP BY Cst_VENTAS_RANGO_TIEMPO_DIA.ANO, Cst_VENTAS_RANGO_TIEMPO_DIA.MES, Cst_VENTAS_RANGO_TIEMPO_DIA.DIA, Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.MONEDA_CODIGO, Cst_VENTAS_HISTORIAL_MONEDA_DETALLE.NOMBRE
    ORDER BY Cst_VENTAS_RANGO_TIEMPO_DIA.ANO, Cst_VENTAS_RANGO_TIEMPO_DIA.MES, Cst_VENTAS_RANGO_TIEMPO_DIA.DIA;
    
    `
} 

export const productos_existencia_Actual = ()=>{
    return `
    SELECT 
        DEPARTAMENTOS_1.NOMBRE AS DEP_PADRE, 
        DEPARTAMENTOS.NOMBRE AS DEP_HIJO, 
        PRODUCTOS_TERMINADOS.CODIGO_PRODUCTO AS REF, 
        PRODUCTOS_TERMINADOS.NOMBRE AS NOMBRE_PROD, 
        PRODUCTOS_TERMINADOS.FACTOR_UNIDAD_SECUNDARIA AS FACTOR_UND_SEC, 
        DEPOSITOS.NOMBRE AS DEPOSITO, 
        PRODUCTOS_TERMINADOS_DEPOSITOS.EXISTENCIA_ACTUAL AS EXISTENCIA, 
        PRODUCTOS_TERMINADOS.MARCA, 
        DEPARTAMENTOS_1.CODIGO as COD_DEP_PADRE, 
        DEPARTAMENTOS.CODIGO AS COD_DEP_HIJO,
        PRODUCTOS_TERMINADOS.ESTATUS, 
        MONEDA.NOMBRE
    FROM 
        MONEDA 
        INNER JOIN (DEPOSITOS 
            INNER JOIN (DEPARTAMENTOS AS DEPARTAMENTOS_1 
                INNER JOIN (DEPARTAMENTOS 
                    INNER JOIN (PRODUCTOS_TERMINADOS_DEPOSITOS 
                        INNER JOIN PRODUCTOS_TERMINADOS 
                        ON PRODUCTOS_TERMINADOS_DEPOSITOS.PRODUCTO_CODIGO = PRODUCTOS_TERMINADOS.CODIGO_PRODUCTO) 
                    ON DEPARTAMENTOS.CODIGO = PRODUCTOS_TERMINADOS.DEPARTAMENTO_CODIGO)
                ON DEPARTAMENTOS_1.CODIGO = DEPARTAMENTOS.DEPARTAMENTO_PADRE) 
            ON DEPOSITOS.CODIGO = PRODUCTOS_TERMINADOS_DEPOSITOS.DEPOSITO_CODIGO) 
        ON MONEDA.CODIGO = PRODUCTOS_TERMINADOS.MONEDA_CODIGO
    WHERE PRODUCTOS_TERMINADOS.ESTATUS='A'
    ORDER BY 
        DEPARTAMENTOS_1.NOMBRE,
        DEPARTAMENTOS.NOMBRE, 
        PRODUCTOS_TERMINADOS.NOMBRE, 
        PRODUCTOS_TERMINADOS_DEPOSITOS.EXISTENCIA_ACTUAL DESC
    `
}

export const productosExistenciaActualTotal = ()=>{
    return `
    SELECT 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_PADRE, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_HIJO, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.REF, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.NOMBRE_PROD, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.FACTOR_UND_SEC, 
        Sum(Cst_PRODUCTOS_T_EXIST_ACTUAL.EXISTENCIA) AS SumaDeEXISTENCIA, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.MARCA, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.COD_DEP_PADRE, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.COD_DEP_HIJO, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.NOMBRE AS Moneda, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.ESTATUS
    FROM (${productos_existencia_Actual()}) AS Cst_PRODUCTOS_T_EXIST_ACTUAL
    GROUP BY 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_PADRE, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_HIJO, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.REF, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.NOMBRE_PROD, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.FACTOR_UND_SEC,
        Cst_PRODUCTOS_T_EXIST_ACTUAL.MARCA, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.COD_DEP_PADRE, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.COD_DEP_HIJO, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.NOMBRE, 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.ESTATUS
    ORDER BY 
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_PADRE DESC ,
        Cst_PRODUCTOS_T_EXIST_ACTUAL.DEP_HIJO, 
        Sum(Cst_PRODUCTOS_T_EXIST_ACTUAL.EXISTENCIA) DESC

    `
}

export const constoInventarioXProducto = ()=>{
    return `
        SELECT 
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.DEP_PADRE,
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.DEP_HIJO, 
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.REF, 
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.NOMBRE_PROD, 
            PRODUCTOS_TERMINADOS.COSTO_UNITARIO AS Costo_Und, 
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.SumaDeEXISTENCIA AS Cantidad,
            IIf(DEP_PADRE='GIFT CARD',0,PRODUCTOS_TERMINADOS.COSTO_UNITARIO* Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.SumaDeEXISTENCIA) AS Costo_TOTAL, 
            PRODUCTOS_TERMINADOS.ULTIMA_FACTURA_COMPRA, 
            Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.Moneda,
            CURRENT_DATE as FECHA,
            extract (year from CURRENT_DATE ) AS ANO, 
            extract (month from CURRENT_DATE ) AS MES, 
            extract ( day from CURRENT_DATE ) AS DIA
        FROM 
            PRODUCTOS_TERMINADOS 
            RIGHT JOIN (${productosExistenciaActualTotal()}) AS Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL 
                ON PRODUCTOS_TERMINADOS.CODIGO_PRODUCTO = Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.REF
        WHERE (Cst_PRODUCTOS_T_EXIST_ACTUAL_TOTAL.ESTATUS)='A';
    `
}